version: '3.9'
services:
  s3manager:
    image: cosmtrek/air:v1.49.0
    working_dir: /usr/src/app
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - 8080:8080
    environment:
      - GOFLAGS=-buildvcs=false
      - ENDPOINT=s3:9000
      - ACCESS_KEY_ID=s3manager
      - SECRET_ACCESS_KEY=s3manager
      - BUCKET=pz-mobile-apk
      - ALLOW_CREATE_BUCKET=false
      - ALLOW_DELETE=false
      - USE_SSL=false
