version: '3.9'
services:
  s3manager:
    container_name: s3manager
    build: .
    ports:
      - 8080:8080
    environment:
      - GOFLAGS=-buildvcs=false
      - ENDPOINT=s3:9000
      - ACCESS_KEY_ID=s3manager
      - SECRET_ACCESS_KEY=s3manager
      - BUCKET=pz-mobile-apk
      - ALLOW_CREATE_BUCKET=false
      - ALLOW_DELETE=false
      - USE_SSL=false